### ISSUE TITLE
Create a basic Result of the quiz 

### ISSUE THREAD

**Issue by JeelRajodiya** [JeelRajodiya/brain-blitz#11]
## Edit this file 
![image](https://github.com/JeelRajodiya/brain-blitz/assets/63534268/f3b26634-d311-43e2-81ff-df87a560e53a)

## This components are good for this task
https://daisyui.com/components/stat
![image](https://github.com/JeelRajodiya/brain-blitz/assets/63534268/f54d1966-74ba-4c12-9a68-2d785c0dc7f2)

**Comment by Codesmith28** [comment]
Ok I'll work on it 👍

**Comment by JeelRajodiya** [comment]
> Ok I'll work on it 👍

If this component needs more information about the result let me know which are those

**Comment by Codesmith28** [comment]
Items required for the ScoreBoard:
> number of questions answered correctly, incorrectly, skipped
> positive score, negative score, grand total score
> avg score (iff med pde toh baaki vandho nthi)
> and if difficulty is enabled:
    - number of questions answered correctly : easy, medium, hard
    - number of questions answered incorrectly : easy, medium, hard
    - number of questions skipped : easy, medium, hard
    
i guess aatli info on the score board is sufficient for now....

**Comment by JeelRajodiya** [comment]
> Items required for the ScoreBoard:
> 
> > number of questions answered correctly, incorrectly, skipped
> > positive score, negative score, grand total score
> > avg score (iff med pde toh baaki vandho nthi)
> > and if difficulty is enabled:
> > - number of questions answered correctly : easy, medium, hard
> > - number of questions answered incorrectly : easy, medium, hard
> > - number of questions skipped : easy, medium, hard
> 
> i guess aatli info on the score board is sufficient for now....

## The required variables are available in the QuizResult.tsx file as an Object 
look for this result variable in the QuizResult.tsx. 
![image](https://github.com/JeelRajodiya/brain-blitz/assets/63534268/6fcde159-5fcb-4511-b611-b2a9ee167530)

## The structure of the result variable is as follows 
> The Easy, Medium and Hard will only be provided when hasDifficultyTags is true

![image](https://github.com/JeelRajodiya/brain-blitz/assets/63534268/14ce9681-a921-47e5-85d6-3ac89cbb317d)

**Comment by Codesmith28** [comment]
can we have it like easyCorrectQuestions,etc...

**Comment by Codesmith28** [comment]
this one done....
