### ISSUE TITLE
Add a loading toast when the user submits the quiz 

### ISSUE THREAD

**Issue by JeelRajodiya** [JeelRajodiya/brain-blitz#13]
Use the same toast that was used for deleting the quiz. 
Just add the text in it "submitting... " 
![image](https://github.com/JeelRajodiya/brain-blitz/assets/63534268/7d17ea7c-efa1-42df-b833-a90ae2fc96b0)

**Comment by Codesmith28** [comment]
loading animation is added
although you may not be able to see it as it is very snappy...
👀
